site_name: Tools for Big Data Analytics - Group 3
theme:
  name: material
  palette:
    primary: blue
    accent: light blue

nav:
  - Architecture: architecture.md
  - Analytics: analytics.md
  - Tools & Platforms: tools.md
  - Results & SDG Impact: results.md
